/*  =========================================================================
    aggregator - generated layer of public API

    Copyright (c) the Authors

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef AGGREGATOR_LIBRARY_H_INCLUDED
#define AGGREGATOR_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <zmq.h>
#include <czmq.h>

//  AGGREGATOR version macros for compile-time API detection
#define AGGREGATOR_VERSION_MAJOR 0
#define AGGREGATOR_VERSION_MINOR 1
#define AGGREGATOR_VERSION_PATCH 0

#define AGGREGATOR_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define AGGREGATOR_VERSION \
    AGGREGATOR_MAKE_VERSION(AGGREGATOR_VERSION_MAJOR, AGGREGATOR_VERSION_MINOR, AGGREGATOR_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined AGGREGATOR_STATIC
#       define AGGREGATOR_EXPORT
#   elif defined AGGREGATOR_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define AGGREGATOR_EXPORT __declspec(dllexport)
#       else
#           define AGGREGATOR_EXPORT
#       endif
#   elif defined AGGREGATOR_EXPORTS
#       define AGGREGATOR_EXPORT __declspec(dllexport)
#   else
#       define AGGREGATOR_EXPORT __declspec(dllimport)
#   endif
#else
#   define AGGREGATOR_EXPORT
#endif

//  Project has no stable classes, so we build the draft API
#undef  AGGREGATOR_BUILD_DRAFT_API
#define AGGREGATOR_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef AGGREGATOR_BUILD_DRAFT_API
typedef struct _aggregator_msg_t aggregator_msg_t;
#define AGGREGATOR_MSG_T_DEFINED
typedef struct _aggregator_broker_t aggregator_broker_t;
#define AGGREGATOR_BROKER_T_DEFINED
#endif // AGGREGATOR_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef AGGREGATOR_BUILD_DRAFT_API
#include "aggregator_msg.h"
#include "aggregator_broker.h"
#endif // AGGREGATOR_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
