/*  =========================================================================
    aggregator_classes - private header file

    Copyright (c) the Authors
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef AGGREGATOR_CLASSES_H_INCLUDED
#define AGGREGATOR_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/aggregator.h"

//  Internal API

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef AGGREGATOR_BUILD_DRAFT_API

#endif // AGGREGATOR_BUILD_DRAFT_API

#endif
